### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lvnilesh** [OfficeDev/xblock-officemix#3]
I setup edX in vagrant virtualbox using production setup instructions from edX git repo then I cloned this repo
```
vagrant ssh
cd ~
git clone https://github.com/OfficeDev/xblock-officemix.git
cd xblock-officemix
pip install -r requirements.txt 
```
failed so I tried 
```
sudo pip install -r requirements.txt
```
Then I enabled in studio as described at 
https://github.com/OfficeDev/xblock-officemix/blob/master/README.md#enabling-in-studio

However, I do not see OfficeMix when I select advanced as described https://github.com/OfficeDev/xblock-officemix/blob/master/README.md#usage

Q1. What am I missing?
Q2. Is `~/` the correct location to clone?
Q3. Is the master correct brand to pull from? I do not see any release or stable marking or others tags in the git repo yet. 
Q4. Is `virtualenv` usage expected? This vagrantbox with edx gets deployed with `virtualenv` already but your documentation is silent so I was not sure. If so, how do I set up so that officemix can be deployed correctly in the edX?

**Comment by kurtb** [comment]
Take a look at the "Deploying to edx-platform" here: https://antoviaque.org/docs/edx/xblock/tutorial.html which provides some nice instructions.

I had cloned the repository outside of the vagrant instance and then mapped it. Although I think cloning within it should work as well. But I believe you need to install as the edxapp user (i.e. do sudo su edxapp prior to the above). You also want to make sure to tweak some of the default values to allow the use of xblocks.

After that I think it should show up.

And yeah master is the correct place to pull from. Adding in a version is a good idea too. I'll look to add a tag.

**Comment by Lamicc** [comment]
Is this problem solved? Same here. I ran every single command and it didn't work.

**Comment by kurtb** [comment]
Should be solved and still working. What problem do you run into when you try to run it?

**Comment by Lamicc** [comment]
@kurtb 
The Xblock didn't show up in the Advanced component after last step
sudo pip install -r requirements.txt
So I ran the following command instead, problem solved.
sudo -u edxapp /edx/bin/pip.edxapp install xblock-officemix/
Thank you anyway.

**Comment by lvnilesh** [comment]
Please consider updating the README.md with explicity clear instructions.

**Comment by lvnilesh** [comment]
These exact steps worked for me. Please doc these in the main readme. Thanks.

```
sudo su edxapp -s /bin/bash
cd /edx/app/edxapp
git clone https://github.com/beacloudgenius/xblock-officemix.git
cd xblock-officemix
exit
cd /edx/app/edxapp
cd xblock-officemix/
sudo pip install -r requirements.txt
cd /edx/app/edxapp
sudo -u edxapp /edx/bin/pip.edxapp install xblock-officemix/

Unpacking ./xblock-officemix
 Running setup.py (path:/tmp/pip-FwWmpk-build/setup.py) egg_info for package from file:///edx/app/edxapp/xblock-officemix

Requirement already satisfied (use --upgrade to upgrade): XBlock in ./venvs/edxapp/src/xblock (from xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): lxml in ./venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in ./venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil in ./venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): pytz in ./venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): webob in ./venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-officemix==0.1)
Requirement already satisfied (use --upgrade to upgrade): six in ./venvs/edxapp/lib/python2.7/site-packages (from python-dateutil->XBlock->xblock-officemix==0.1)
Installing collected packages: xblock-officemix
 Running setup.py install for xblock-officemix

Successfully installed xblock-officemix
Cleaning up...
ubuntu@ip:/edx/app/edxapp$

```
